MANDP_CLIENT_SRC 		= client.c
MANDP_SERVER_SRC 		= server.c
BONUSP_SERVER_SRC 		= server_bonus.c
BONUSP_CLIENT_SRC 		= client_bonus.c

MANDP_CLIENT_EXE		= client
MANDP_SERVER_EXE		= server
BONUSP_CLIENT_EXE		= client_bonus
BONUSP_SERVER_EXE		= server_bonus
PRINTF_EXE				= libftprintf.a

SRC_DIR					= sources/
PRINTF_DIR				= ft_printf/

MANDP_CLIENT_PREFIX     = $(addprefix $(SRC_DIR), $(MANDP_CLIENT_SRC))
MANDP_SERVER_PREFIX     = $(addprefix $(SRC_DIR), $(MANDP_SERVER_SRC))
BONUSP_CLIENT_PREFIX	= $(addprefix $(SRC_DIR), $(BONUSP_CLIENT_SRC))
BONUSP_SERVER_PREFIX	= $(addprefix $(SRC_DIR), $(BONUSP_SERVER_SRC))

MANDP_CLIENT_OBJ		= $(MANDP_CLIENT_PREFIX:.c=.o)
MANDP_SERVER_OBJ 		= $(MANDP_SERVER_PREFIX:.c=.o)
BONUSP_CLIENT_OBJ		= $(BONUSP_CLIENT_PREFIX:.c=.o)
BONUSP_SERVER_OBJ		= $(BONUSP_SERVER_PREFIX:.c=.o)

CC						= cc
C_FLAGS			 		= -Wall -Werror -Wextra
HEADER1					= headers/minitalk.h
HEADER2					= headers/minitalk_bonus.h
RM				 		= rm -rf

all : $(MANDP_CLIENT_EXE) $(MANDP_SERVER_EXE)

$(MANDP_CLIENT_EXE) : $(MANDP_CLIENT_OBJ) $(PRINTF_DIR)/$(PRINTF_EXE) $(HEADER1)
	$(CC) $(C_FLAGS) $(MANDP_CLIENT_OBJ) $(PRINTF_DIR)/$(PRINTF_EXE) -o $(MANDP_CLIENT_EXE)

$(MANDP_SERVER_EXE) : $(MANDP_SERVER_OBJ) $(PRINTF_DIR)/$(PRINTF_EXE) $(HEADER1)
	$(CC) $(C_FLAGS) $(MANDP_SERVER_OBJ) $(PRINTF_DIR)/$(PRINTF_EXE) -o $(MANDP_SERVER_EXE)

bonus : $(BONUSP_CLIENT_EXE) $(BONUSP_SERVER_EXE)

$(BONUSP_CLIENT_EXE) : $(BONUSP_CLIENT_OBJ) $(PRINTF_DIR)/$(PRINTF_EXE) $(HEADER2)
	$(CC) $(C_FLAGS) $(BONUSP_CLIENT_OBJ) $(PRINTF_DIR)/$(PRINTF_EXE) -o $(BONUSP_CLIENT_EXE)

$(BONUSP_SERVER_EXE) : $(BONUSP_SERVER_OBJ) $(PRINTF_DIR)/$(PRINTF_EXE) $(HEADER2)
	$(CC) $(C_FLAGS) $(BONUSP_SERVER_OBJ) $(PRINTF_DIR)/$(PRINTF_EXE) -o $(BONUSP_SERVER_EXE)

$(PRINTF_DIR)/$(PRINTF_EXE):
	make -C $(PRINTF_DIR)

clean	:
	make clean -C $(PRINTF_DIR)
	$(RM) $(MANDP_CLIENT_OBJ) $(MANDP_SERVER_OBJ) $(BONUSP_CLIENT_OBJ) $(BONUSP_SERVER_OBJ)

fclean	: clean
	make fclean -C $(PRINTF_DIR)
	$(RM) $(MANDP_CLIENT_EXE) $(MANDP_SERVER_EXE)
	$(RM) $(BONUSP_CLIENT_EXE) $(BONUSP_SERVER_EXE)

re		: fclean all

.PHONY	: clean fclean re bonus all
